### ISSUE TITLE
ASDF Style warning

### ISSUE THREAD

**Issue by Hellseher** [alex-gutev/static-dispatch#3] opened 2021-02-03 01:22 UTC
```WARNING:
   Deprecated recursive use of (ASDF/OPERATE:OPERATE 'ASDF/LISP-ACTION:LOAD-OP
   '("static-dispatch/test")) while visiting
   (ASDF/LISP-ACTION:TEST-OP "static-dispatch/test") - please use proper
   dependencies instead```

**Comment by alex-gutev** [comment] 2021-04-03 12:54
I'm unable to reproduce this warning. What version of ASDF are you using?

**Comment by Hellseher** [comment] 2021-04-17 19:58
It's ASDF v3+
https://common-lisp.net/project/asdf/asdf.html#Complex-component-names-1

**Comment by alex-gutev** [comment] 2021-04-18 08:27
I believe it's related to the use of the prove testing library, in particular it's `:TEST-FILE` ASDF component type. It's no longer maintained has a lot of other bugs, so I'll be transitioning away from it to Fiveam.

**Comment by alex-gutev** [comment] 2021-05-13 17:18
I've moved away from Prove to FiveAM, which doesn't use custom ASDF components. I don't have any warnings on the latest ASDF 3.3.4. If this solve the problem I'll close this issue.

**Comment by Hellseher** [comment] 2021-05-15 10:57
Hi,

Thank you for solving it so quickly I'll send patch to Guix to update the package to the current release.

PS. Big plus for using annotated tags! Majority of Common Lisp community just ignore it :)

**Closed** 2021-05-15 11:23 UTC
